services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  T3\Mbox\Controller\MboxModuleController: ~
  T3\Mbox\ViewHelpers\ParseHtmlViewHelper: ~
  T3\Mbox\XClass\MboxTransport: ~
